on:
  schedule:
    - cron: '46 07 * * *'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::jsonlite
            any::ggtext
            any::ggimage
            any::lubridate
            any::sysfonts
            any::showtext

      - name: Import data
        run: Rscript -e 'source("beach_walk_figure_generator.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f beach_walk.png beach_walk_dark.png
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
